# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '~> 7.0.0'

gem 'graphql'
gem 'puma', '~> 3.7'
gem 'search_object'
gem 'sqlite3'

gem 'graphiql-rails', group: :development
